# Generated by Django 5.1.4 on 2025-02-18 17:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PelletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_achat', models.DateField(default=datetime.date.today)),
                ('prix_unite', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('poid_sac', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('quantite_initiale', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Consomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('isPerte', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pellet_mgmt_app.pellettype')),
            ],
        ),
    ]
